version: "3"
services:
    nm_app:
        container_name: nm_app
        build:
            context: ./node
        networks:
            network_monitor:
                ipv4_address: ${SERVER_IP}
        volumes:
            - server:/usr/src/app/server
            - webapp:/usr/src/app/webapp
        ports:
            - ${SERVER_PORT}:9500
        tty: true
        stdin_open: true
    # nm_webapp:
    #     container_name: nm_webapp
    #     build:
    #         context: .
    #         args:
    #             ROS_DISTRO: ${ROS_DISTRO}
    #             ROS_MASTER_URI: http://${ROS_MASTER_IP}:${ROS_MASTER_PORT}
    #             SCRIPT_FOLDER: roslaunch
    #     networks:
    #         witty:
    #             ipv4_address: ${ROSRUN_NODE_1}
    #     env_file:
    #         - .env
    #         - ./envs/.env_turtlebot_gazebo
    #     volumes:
    #         - /tmp/.X11-unix:/tmp/.X11-unix:rw
    #         - workspace:/root/catkin_ws/src
    #     tty: true
    #     stdin_open: true
    #     depends_on:
    #         - roscore

networks:
    network_monitor:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

volumes:
    server:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${SERVER_APP}
    webapp:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${WEB_APP}
