version: "3"
services:
    nm_app:
        container_name: nm_app
        build:
            context: ./node
        networks:
            network_monitor:
                ipv4_address: ${SERVER_IP}
        volumes:
            - server:/usr/src/app/server
            - webapp:/usr/src/app/webapp
        ports:
            - ${SERVER_PORT}:9500
        tty: true
        stdin_open: true
    nm_db:
        container_name: nm_db
        build:
            context: ./mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            network_monitor:
                ipv4_address: ${DB_IP}
        volumes:
            - db:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        env_file:
            - .env
        tty: true
        stdin_open: true

networks:
    network_monitor:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

volumes:
    server:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${SERVER_APP}
    webapp:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${WEB_APP}
    db:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${DB_APP}
